### ISSUE TITLE
Die for + flags is not very informative

### ISSUE THREAD

**Issue by csdvrx** [G4Vi/Perl-Dist-APPerl#3]
When a + option in the json is misconfigured (missing the realkey), the message is not very informative.

Suggestion: on line 1282 of Perl/Dist/APPerl.pm add $realkey

                exists $itemconfig{$realkey} or die("cannot append without existing key: " . $realkey);

Other die() messages may benefit from similar changes

**Comment by G4Vi** [comment]
Improving those messages with the offending data is a great idea. A PR would be welcome, but added to the TODO list otherwise.

**Comment by G4Vi** [comment]
Added in [v0.3.0](https://github.com/G4Vi/Perl-Dist-APPerl/releases/tag/v0.3.0)
