### ISSUE TITLE
Suggestion : default config for argv[0] script execution

### ISSUE THREAD

**Issue by kal247** [G4Vi/Perl-Dist-APPerl#5]
Hello, just an improvement suggestion.

If argv[0] doesn't match any embedded script, APPerl will enter the Perl interpreter.

When used to distribute an application, this behaviour seems wrong from the end-user point of view :

- changing the file name should not break the application.
- the Perl interpreter should not be entered.

PAR::Packer has the same annoying behaviour (will exit if argv[0] is unknown).

**Comment by G4Vi** [comment]
I have an idea for this:
* add a variable, `static char BinaryName[256];` that is empty at perl compile time. Somehow save or find the file offset of `BinaryName`
* enable `apperlm` to patch `BinaryName`
* When `BinaryName[0] == 0`, do `argv[0]` script execution.
* Otherwise attempt to load a script from `/zip/bin/BinaryName`. For simplicity, if it fails it would just have the message "Can't open perl script "/zip/bin/BinaryName": No such file or directory", end users will never see that message unless the application author set an incorrect `BinaryName`

**Comment by kal247** [comment]
I was thinking the opposite, like a fallback :

1. do `argv[0]` script execution if found in `/zip/bin`
2. exec default script if defined/exists/whatever/found in `/zip/bin`
3. otherwise run perl

This would be useful for collections of scripts.

**Comment by G4Vi** [comment]
That seems more flexible, I'd also like to add, before step 1:

If `argv[0]` without extension is `perl` run perl, so the binary can always be used to run perl even if a default script is set without needing to binary patch the binary to clear out the default script string.

**Comment by G4Vi** [comment]
@kal247

Implemented in https://github.com/G4Vi/Perl-Dist-APPerl/commit/3ba40a8f3cc8f950ef8aa47b0c7fb58ae6f12e4e and https://github.com/G4Vi/perl5/commit/9fdd50f323c92d465011c9f0857819edcc41be28

Just add `"default_script":"/zip/bin/BinaryName"` to a config. You should be able to try it from the files build artifacts of the actions run: https://github.com/G4Vi/Perl-Dist-APPerl/actions/runs/3825447693

**Comment by devereaux** [comment]
> That seems more flexible, I'd also like to add, before step 1:
> 
> If `argv[0]` without extension is `perl` run perl, so the binary can always be used to run perl even if a default script is set without needing to binary patch the binary to clear out the default script string.

It would also be nice to have an override flag: even if a default script is set, run vanilla perl with the flag -z and an internal script with -Z

So perlape.com would run normally as before, unless you run it as perlape.com -z which would let you execute scripts (ex: perlape.com -z file.pl would run perl with ./file.pl ) 

The scripts could also be within the ZIP part of perlape.com with another flag (ex: perlape.com -Z internal.pl would run perl with /zip/bin/internal.pl

**Comment by G4Vi** [comment]
I added script execution from environment variable `APPERL_SCRIPTNAME`.

Using  `APPERL_SCRIPTNAME` INSTEAD of `argv[0]` munging (passing a different `argv[0]` than programname) is highly recommended in scripts as it works on all platforms and APE loaders. There should be no problems with symlink or rename execution of APPerl to run different scripts.

 In pseudo-perl, apperl's script execution now roughly works as follows:
```perl
my $inputscriptname = $ENV{APPERL_SCRIPTNAME} // $0; # the environment variable or argv[0]
my $scriptname;
if($inputscriptname ne 'perl') {
    $inputscriptname = "/zip/bin/$inputscriptname";
    if(-f $inputscriptname) {
        $scriptname = $inputscriptname;
    }
    elsif(defined APPERL_DEFAULT_SCRIPT) { # the scriptname stored in the binary
        $scriptname = APPERL_DEFAULT_SCRIPT;
    }
}
```
For example if you packed
`forker`:
```perl
#!/usr/bin/perl
use strict; use warnings;
print "forking\n";
my $pid = fork();
defined($pid) or die "$!";
if($pid == 0) {
    $ENV{APPERL_SCRIPTNAME} = 'child';
    exec { $^X } ($^X);
    die "$!";
}
print "waiting for $pid\n";
waitpid($pid, 0);
print "$pid exited\n";
```
and `child`:
```perl
#!/usr/bin/perl
use strict; use warnings;
print "ran child\n";
```
into `forker.com` and ran the output should look like
```bash
forking
waiting for 52691
ran child
52691 exited
```

I am not interested in adding any command line flags (especially short ones) to `APPerl` to avoid accidentally creating a mess if someday Perl decides to use them. The `-Z` flag could probably be implemented as script and packed into APPerl if desired.

**Comment by kal247** [comment]
Wow, you're fast. I've done some tests, but I'm not sure I've done everything right.

- With `src/hello` included in config as `"bin" : [ "src/hello" ]`, both symlinks `hello` and `hello.pl` work. `$0` is set to /zip/bin/hello in both cases.
- With the same script renamed as`src/hello.pl` and included in config as `"bin" : [ "src/hello.pl" ]`, then both symlinks `hello` and `hello.pl` don't work.
- After creating `src/default_script` and changing the config as follow, I've tested a symlink `xxx` but it didn't work :

```
{
   "defaultconfig" : "my_nobuild_config",
   "apperl_configs" : {
      "my_nobuild_config" : {
         "base" : "nobuild-v0.1.0",
         "dest" : "perl.com",
         "desc" : "description of this config",
		 "zip_extra_files" : {
		 	"bin" : [ "src/hello", "src/script1", "src/script2", "src/default_script" ]
	 	 },
		 "default_script" : "/zip/bin/default_script"
      }
   }
}
```

- no more success with `APPERL_SCRIPTNAME=/zip/bin/default_script`

**Comment by G4Vi** [comment]
@kal247  Thanks for trying it out.

> * With the same script renamed as`src/hello.pl` and included in config as `"bin" : [ "src/hello.pl" ]`, then both symlinks `hello` and `hello.pl` don't work.

This is expected to me. Currently, for argv[0] execution it only checks for
 `/zip/bin/basename_without_last_file_extension(argv[0])`. I'm not sure which if any of those make the most sense to add yet.

For setting `APPERL_DEFAULT_SCRIPT` and the `APPERL_SCRIPTNAME=/zip/bin/default_script perl.com` execution with a nobuild config, Could you please verify you updated `src/perl.com` to use the binaries from the build artifacts latest actions run on `master`?

**Comment by kal247** [comment]
> This is expected to me. Currently, for argv[0] execution it only checks for
> `/zip/bin/basename_without_last_file_extension(argv[0])`. I'm not sure which if any of those make the most sense to add yet.

Now I've seen it in USAGE, sorry.

> For setting `APPERL_DEFAULT_SCRIPT` and the `APPERL_SCRIPTNAME=/zip/bin/default_script perl.com` execution with a nobuild config, Could you please verify you updated `src/perl.com` to use the binaries from the build artifacts in the latest actions run on `master`?

I'm 100% sure (okay, 99.9%). Is there a way to check the output binary for "version" ?

**Comment by G4Vi** [comment]
@kal247 I attempted to reproduce. I downloaded `full` from https://github.com/G4Vi/Perl-Dist-APPerl/actions/runs/3853036583 , extracted `perl.com` to `src/`. I created the scripts with the contents `print "I am $0\n";`

Building should look something like this, note the line `patching default script at 9802998`, are you getting a similar line when running `apperlm build`?
```bash
(base) username@computer:~/apperl-script-execution$ perl -I ../Perl-Dist-APPerl/lib ../Perl-Dist-APPerl/script/apperlm build
rm -rf /home/username/apperl-script-execution/.apperl/o/my_nobuild_config
mkdir -p /home/username/apperl-script-execution/.apperl/o/my_nobuild_config/tmp
/home/username/apperl-script-execution/src/perl.com -e use Config; print $Config{prefix}
/home/username/apperl-script-execution/src/perl.com -e use Config; print $Config{version}
/home/username/apperl-script-execution/src/perl.com -e use Config; print $Config{archname}
cp /home/username/apperl-script-execution/src/perl.com /home/username/apperl-script-execution/.apperl/o/my_nobuild_config/tmp/perl.com
chmod 755 /home/username/apperl-script-execution/.apperl/o/my_nobuild_config/tmp/perl.com
cd /home/username/apperl-script-execution/.apperl/o/my_nobuild_config/tmp/zip
_copy_recursive /home/username/apperl-script-execution/src/hello bin
_copy_recursive /home/username/apperl-script-execution/src/script1 bin
_copy_recursive /home/username/apperl-script-execution/src/script2 bin
_copy_recursive /home/username/apperl-script-execution/src/default_script bin
zip -r /home/username/apperl-script-execution/.apperl/o/my_nobuild_config/tmp/perl.com lib bin
        zip warning: name not matched: lib
updating: bin/ (stored 0%)
  adding: bin/default_script (stored 0%)
  adding: bin/script2 (stored 0%)
  adding: bin/script1 (stored 0%)
  adding: bin/hello (stored 0%)
patching default script at 9802998
mv /home/username/apperl-script-execution/.apperl/o/my_nobuild_config/tmp/perl.com /home/username/apperl-script-execution/.apperl/o/my_nobuild_config/perl.com
cd /home/username/apperl-script-execution
cp /home/username/apperl-script-execution/.apperl/o/my_nobuild_config/perl.com perl.com
```

In order for `APPERL_DEFAULT_SCRIPT` script to run, `APPERL_SCRIPTNAME` and `argv[0]` must not be `perl` The `dest` variable could be set to change the outputname instead of `mv` also:
```bash
(base) username@computer:~/apperl-script-execution$ ./perl.com 
^C
(base) username@computer:~/apperl-script-execution$ mv perl.com abcdef.com
(base) username@computer:~/apperl-script-execution$ ./abcdef.com 
I am /zip/bin/default_script
```
Demo of `APPERL_SCRIPTNAME`
```bash
(base) username@computer:~/apperl-script-execution$ mv abcdef.com perl.com
(base) username@computer:~/apperl-script-execution$ APPERL_SCRIPTNAME=/zip/bin/script1 ./perl.com
I am /zip/bin/script1
(base) username@computer:~/apperl-script-execution$ APPERL_SCRIPTNAME=script1 ./perl.com
I am /zip/bin/script1
```

As for checking what version, currently I'd just check the date in `src/perl.com -V`. For that full build it's `Compiled at Jan  6 2023 06:06:44`.

**Comment by G4Vi** [comment]
@kal247

For now you have to install from github. I haven't made a release yet, my apologies if this wasn't clear.

If you use `cpanm`:

```bash
cpanm -U Perl::Dist::APPerl
cpanm https://github.com/G4Vi/Perl-Dist-APPerl.git@master
```

**Comment by kal247** [comment]
Stupid me, now it makes sense and it works, of course.
I was confused by the fact that `perl.com` can be bootstrapped by itself, and I hadn't even updated APPerl.
Thanks for your help.

**Comment by G4Vi** [comment]
Np, glad it's now working.
