### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by avih** [G4Vi/Perl-Dist-APPerl#7]
Cosmopolitan has seen many improvements, and a new release, and perl has newer versions too at the 5.x line (though the patchset of the cosmo branch [here](https://github.com/G4Vi/perl5) fail to apply starting at perl 5.37.3 IIRC).

Would you consider releasing an updated build?

Thanks in advance, and for the existing releases :)

**Comment by G4Vi** [comment]
It's on my list. I'll try to get to it soon, but no promises.

I think I'll update cosmo and do one more round 5.36 based releases before making 5.38 builds. It will be good to get rid of some of the cosmo specific hacks like switch statement to if statement rewrites. It would be nice to switch this to `cosmocc`, but not sure how easy that will be.

**Comment by avih** [comment]
Appreciated.

**Comment by G4Vi** [comment]
[v0.4.0](https://github.com/G4Vi/Perl-Dist-APPerl/releases/tag/v0.4.0) (with some 5.36.1 builds)

**Comment by avih** [comment]
Thanks.

I think there's an issue though, at least with perldoc. In cmd.exe env (`perldoc.com` is a symlink to `perl.com`):
```
D:\run\utils>perldoc perl
Invalid parameter - ""/tmp/2u2BER4MdH""

D:\run\utils>perl.com /zip/bin/perldoc perl
Invalid parameter - ""/tmp/yWqDYIi3RS""
```

Looks like incorrect double quotation issue?

**Comment by G4Vi** [comment]
Something probably changed with cosmo's exec quote handling. I won't be able to debug this until next week. I recommend sticking with 0.3 in the meantime.

The `.com.dbg` contains debugging symbols, it may be used with gdb when debugging the `.com`. It's the ELF emitted from the compiler before the APE is created.

**Comment by avih** [comment]
> Please try out [v0.5.0-rc1](https://github.com/G4Vi/Perl-Dist-APPerl/releases/tag/v0.5.0-rc1) and let me know if the quote issue is back to how it was in 0.3.

Apologies for the delay.

Looks like "full" and "full-vista" are OK (it displays the docs).

Looks like "small" and "small-vista" don't display the docs:
```sh
$ ./perl-small.com /zip/bin/perldoc perl
Can't open perl script "/zip/bin/perldoc": ENOENT/2/No such file or directory/0/The operation completed successfully
```

I presume the small variants don't include perldoc at the binary?

All the variants are from this download https://github.com/G4Vi/Perl-Dist-APPerl/releases/download/v0.5.0-rc1/APPerl-v0.5.0-all.zip

**Comment by G4Vi** [comment]
Thanks for trying it out, glad that works.

Correct, the small variants do not include perldoc as the dependencies needed for it bloat the size of APPerl.

To build APPerl with updated cosmo, I'd like to switch APPerl to build with the [superconfigure](https://github.com/ahgamut/superconfigure) approach.

**Comment by G4Vi** [comment]
New version using Cosmopolitan v3.3.10 https://github.com/G4Vi/Perl-Dist-APPerl/releases/tag/v0.6.0

**Comment by avih** [comment]
> New version using Cosmopolitan v3.3.10

Looks good. Thanks.
